version: '3.8'
services:
  db:
    image: postgres
    hostname: postgres
    ports:
      - "6432:5432"
    env_file:
      - .env_docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_docker
    volumes:
      - .:/capp
    ports:
      - "8008:8000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    env_file:
      - .env_docker
    restart: unless-stopped

volumes:
  postgres-data: