"""do migration

Revision ID: aa549058fba6
Revises: 
Create Date: 2023-01-27 05:22:04.491179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa549058fba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, cycle=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('server', sa.String(length=20), nullable=True),
    sa.Column('pin_code', sa.String(length=4), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'server', name='already_existed')
    )
    op.create_table('validation',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, cycle=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pin_code', sa.String(length=4), nullable=False),
    sa.Column('url', sa.String(length=20), nullable=False),
    sa.Column('time_email_sent', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation')
    op.drop_table('user')
    # ### end Alembic commands ###
